#!/bin/sh
#
prog=cryplist
usage="$prog domain-name"
#
#	Create a suggested list of tests for a domain, based on various 
#	domain names. Very crude, but a good place to start.
#
#	Needs dig(1). On linux:
#		apt-get install dnsutils
#	FreeBSD:
#		pkg install bind-tools
#	Mac:
#

NAME=cryp

TMPDIR=${TMPDIR:-/tmp}
WRKDIR=$TMPDIR/$prog
mkdir -p $WRKDIR #2>/dev/null
rm -rf $WRKDIR/*

case $# in
1)	domain="$1";	shift;;
*)
	echo "$usage" 1>&2
	exit 1
esac


dig web.$domain www.$domain | awk '
	$1 ~ /^(web|www)\..*/ && $4 == "A" {
		print $5}' | sort -u |
while read webserver
do
	echo ${NAME}_web $webserver
done


dig vpn.$domain | awk '
	$1 ~ /^(vpn)\..*/ && $4 == "A" {
		print $5}' | sort -u |
while read vpnserver
do
	echo ${NAME}_vpn $vpnserver
done


dig ftp.$domain | awk '
	$1 ~ /^(vpn)\..*/ && $4 == "A" {
		print $5}' | sort -u |
while read ftpservers
do
	echo ${NAME}_ftps $ftpservers
done


dig any $domain smtp.$domain smtps.$domain \
	imap.$domain imaps.$domain pop3.$domain pop3s.$domain >$WRKDIR/digout

awk <$WRKDIR/digout '
	$4 == "MX" { print $NF}' | sort -u |
while read mailserver
do
	echo ${NAME}_pop3s $mailserver
	echo ${NAME}_imaps $mailserver
	echo ${NAME}_smtps $mailserver
done
